dist: bionic
language: node_js
node_js:
  - "node"
cache: npm

before_script:
  - npm install -g gulp-cli

script:
  - gulp
  - mkdir ghpages
  - cp build/playable_ad/js-web/playable_ad/playable_ad.html ghpages/index.html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: ghpages
  on:
    branch: master
