name: Build example

on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    # nightly at 05:00 on the 1st and 15th
    - cron: 0 5 1,15 * *

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Install Java ♨️
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "11"

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Zstd
        run: |
          sudo apt-get install -y zstd

      - name: Build 🔧
        run: |
          lsb_release -a

          npm install --global gulp-cli

          cd playable_ad
          npm install
          gulp

          mkdir public
          mv build/output_js-web/playable_ad_example/playable_ad_example.html public/index.html

      - name: Deploy to Pages 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: playable_ad/public
